spring:
  application:
    name: rentdrive-api

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:rentdrive}?zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER:rentdrive}
    password: ${MYSQL_PASSWORD:rentdrive}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

  flyway:
    enabled: false
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8080
